# _plugins/build.rb
require 'time'
require 'jekyll'
require 'fileutils'

module Jekyll
  class ExtBuildInfoGenerator < Generator
    safe true
    priority :highest

    def generate(site)
      Jekyll.logger.info "BuildInfo v0.3:", "A plugin for LexSite's versioning mechanic."
      Jekyll.logger.info "", "Copyright (c) 2025 Lexibyte."
      Jekyll.logger.info "BuildInfo:", "Plugin 'ExtBuildInfoGenerator' started."

      build_number_file_path = File.join(site.source, 'version.txt')
      current_incremental_number = 0

      begin
        if File.exist?(build_number_file_path)
          current_incremental_number = File.read(build_number_file_path).to_i
          Jekyll.logger.info "BuildInfo:", "Read initial build number from #{build_number_file_path}: #{current_incremental_number}"
        else
          Jekyll.logger.warn "BuildInfo:", "version.txt not found at #{build_number_file_path}. Starting build number from 0."
        end
      rescue => e
        Jekyll.logger.error "BuildInfo Error:", "Failed to read version.txt: #{e.message}. Using 0."
        current_incremental_number = 0
      end

      current_incremental_number += 1

      if ENV['GITHUB_ACTIONS'].nil?
        begin
          File.write(build_number_file_path, current_incremental_number.to_s)
          Jekyll.logger.info "BuildInfo:", "Incremented and persisted build number to #{build_number_file_path}: #{current_incremental_number}"
        rescue => e
          Jekyll.logger.error "BuildInfo Error:", "Failed to write version.txt: #{e.message}. Build number not persisted locally."
        end
      else
        Jekyll.logger.info "BuildInfo:", "Running in GitHub Actions. Using committed build number without incrementing/persisting locally."
      end

      build_patch_number = current_incremental_number

      utc_now = Time.now.utc
      cst_offset_seconds = -6 * 3600
      cst_time = utc_now + cst_offset_seconds
      timestamp = cst_time.strftime("%y%m%d-%H%M")
      Jekyll.logger.info "BuildInfo:", "Generated timestamp: #{timestamp} (CST)"

      build_info_js_content = <<-JS
// This file is automatically generated by Jekyll's _plugins/build.rb
// Do not edit directly.
const GLOBAL_BUILD_MAJOR = "0";
const GLOBAL_BUILD_MINOR = "1";
const GLOBAL_BUILD_PATCH = "#{build_patch_number}";
const GLOBAL_BUILD_TIMESTAMP = "#{timestamp}";
      JS

      # KEY CHANGE HERE: Write to source/resources/js
      output_dir = File.join(site.source, 'resources', 'js') # <--- CHANGE THIS LINE!
      FileUtils.mkdir_p(output_dir) unless File.directory?(output_dir)

      output_file_path = File.join(output_dir, 'buildnumber.js') # <--- Retain filename

      File.write(output_file_path, build_info_js_content)
      Jekyll.logger.info "BuildInfo:", "Generated buildnumber.js at: #{output_file_path}"
    end
  end
end
